# Generated by Django 2.2.2 on 2019-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default='none@mail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
